# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf3343df51052f679c0b8ca0139cd594723cbda78f83f7c39ec9a229726da7fda87a465b20b7209f8f6934cf4cda88f94064ddd1653b3fac1c2783463994867

test:
  secret_key_base: 4d4bac24170ba560d19cbc9dd52c0cf3b97b5130039ad897bdd2a6a75ff6d9a07accc0390abea7aaa16226c18570327c3fe1c82637af75ae4b7d939cfc3a0efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
